### ISSUE TITLE
Statistic Labels invisible after language change

### ISSUE THREAD

**Issue by ComradePhilos** [ComradePhilos/CoYOTe#12]
I found a bug that I could not fix until now. The labels shown in the picture are invisible after changing the language. Maybe this is a Lazarus-Bug!?

![bug](https://cloud.githubusercontent.com/assets/6881662/3470594/e7b3726c-02bb-11e4-8b8a-2e5962ec7071.png)

**Comment by ComradePhilos** [comment]
I found out, that this happened in Lazarus 1.2.2. on Windows, but on Ubuntu 14.04 and Lazarus 1.2.4 all labels are visible as they ought to be.

**Comment by ComradePhilos** [comment]
Figured out it was a windows' refreshing problem. Using a manual refresh/repaint of the parent component, I managed to fix it.

**Comment by exel202** [comment]
You're such a pro.
