### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by ComradePhilos** [ComradePhilos/CoYOTe#4]
The panel with buttons in it needs to be replaced with a real toolbar in future. This will improve the "look & feel".

**Comment by exel202** [comment]
What do you mean with real toolbar ?

**Comment by ComradePhilos** [comment]
There is a Component TToolbar in the Lazarus LCL, which acts like a toolbar you know from several GUI-programmes. The "toolbar" now is basically a TPanel with some TButtons on it... a DIY-Toolbar =P

**Comment by ComradePhilos** [comment]
Added a real toolbar now! Works the same as it did before, but contributes to a unified "look & feel" now. ;)

**Comment by ComradePhilos** [comment]
The Toolbars can now get a new color via the color theme chooser.
