### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by exel202** [ComradePhilos/CoYOTe#8]
We are now supporting MacOS. Currently there are no bugs that we know, but feel free to test.

I attached some screenshots.
![1](https://cloud.githubusercontent.com/assets/3188007/2958563/a25a58ea-daaa-11e3-87ac-d2f304558e7e.png)
![2](https://cloud.githubusercontent.com/assets/3188007/2958564/a26082ba-daaa-11e3-803e-96354af31679.png)
![3](https://cloud.githubusercontent.com/assets/3188007/2958565/a2645818-daaa-11e3-8915-738ddae0aa6f.png)
![4](https://cloud.githubusercontent.com/assets/3188007/2958566/a269e382-daaa-11e3-9508-7b0c2bd3355d.png)

**Comment by ComradePhilos** [comment]
Everyone, Please note that not every executable can be updated with each commit, although you will find most executables in the repository, too! But with no warranty they are up tp date. If you don't want to compile the programme you should go for the actual (soon available) release-versions!
